pipeline:
  identifier: Build_Gcp_DevSecOps_Repo_1689578214614
  name: Build Gcp-DevSecOps-Repo
  orgIdentifier: default
  projectIdentifier: AkshataOholPersonal
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Akshata-Ohol-29-Personal/Gcp-DevSecOps-Repo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
